### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by JonathanMerritt** [tranngoclam/movie-booking#1]
I believe I can help out and improve on some things. If you are interested let me know.

Mainly surrounding the recyclerview, holders, states and their injections. 

Would be a few pulls.

**Comment by tranngoclam** [comment]
Thanks for your support
Please make PRs and we'll discuss later

**Comment by JonathanMerritt** [comment]
Will do, just making sure before starting on them.

**Comment by JonathanMerritt** [comment]
@tranngoclam In case you want to track the changes before I make any pulls. [JonathanMerritt/movie-booking](https://github.com/JonathanMerritt/movie-booking)

**Comment by tranngoclam** [comment]
I have seen your changes, it's good 👍 
Pls make a PR :D

**Comment by JonathanMerritt** [comment]
Ok. It will be incomplete in areas however. It's mainly for preparations.

**Comment by JonathanMerritt** [comment]
All done with this I think. I'll close this now.

If you want anymore help with anything just let me know.
